### PR TITLE
Add a ui-test

### LINKED ISSUE #9: Add ui-tests with playwright

### PR DESCRIPTION
**Pull request by martinRenou**
Fix #9

### CODE REVIEW

**Comment by martinRenou** [comment]
please update playwright snapshots

**Comment by martinRenou** [comment]
Tests are too flaky... With bqplot taking ages to render properly and readjust its layout.

**Comment by trungleduc** [comment]
please update playwright snapshots

**Comment by martinRenou** [comment]
Thanks a lot!!

**Pull request merged**
