### PR TITLE
Write links in session file

### PR DESCRIPTION
**Pull request by brichet**
Fix https://github.com/QuantStack/gluepyter/issues/84

### CODE REVIEW

**Comment by trungleduc** [comment]
Thanks @brichet, could you do this test with the `session3` file?

https://github.com/QuantStack/gluepyter/blob/2897c4f6a8335dd362de19ac3d35fe5b4d543b36/gluepyter/tests/test_ydoc.py#L15-L22

**Comment by brichet** [comment]
> Thanks @brichet, could you do this test with the `session3` file?

Do you think this is necessary ? I added identity links in the `session.glu`, so the links are already tested now (if I remove my code the test fails). The `session3.glu` includes advanced links, we are not fully supporting it right now.

**Comment by trungleduc** [comment]
> > Thanks @brichet, could you do this test with the `session3` file?
> 
> Do you think this is necessary ? I added identity links in the `session.glu`, so the links are already tested now (if I remove my code the test fails). The `session3.glu` includes advanced links, we are not fully supporting it right now.

ah ok, I missed this part.

**Review by martinRenou — APPROVED** [review]
Thanks!

**Pull request merged**
